# Generated by Django 5.2.5 on 2025-08-26 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0003_alter_document_active_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="active_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
